# Generated by Django 5.2.10 on 2026-01-31 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('user_role', models.CharField(choices=[('Студент', 'Студент'), ('Предподаватель', 'Предподаватель')], max_length=20)),
                ('full_name', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(upload_to='profile_picture/')),
                ('bio', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='course',
            name='type_category',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='status',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(upload_to='video/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=30, max_digits=100)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='udemy_app.submission')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udemy_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_image', models.FileField(upload_to='question_image/')),
                ('title', models.CharField(max_length=100)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udemy_app.exam')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udemy_app.userprofile')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udemy_app.userprofile'),
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В')], max_length=5)),
                ('variant_text', models.TextField()),
                ('true_variant', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udemy_app.examquestion')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='udemy_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='udemy_app.userprofile')),
                ('variants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udemy_app.variants')),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
