# Generated by Django 5.2.10 on 2026-02-01 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy_app', '0004_category_name_en_category_name_ky_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='course',
        ),
        migrations.AddField(
            model_name='review',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='udemy_app.course'),
            preserve_default=False,
        ),
    ]
