# Generated by Django 5.2.10 on 2026-02-02 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy_app', '0006_alter_certificate_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionanswer',
            name='status_choices',
            field=models.CharField(choices=[('Аткарган жок', 'Аткарган жок'), ('Аткарды', 'Аткарды')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='udemy_app.cart'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='udemy_app.category'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='udemy_app.course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='udemy_app.course'),
        ),
        migrations.AlterField(
            model_name='submissionanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udemy_app.submission'),
        ),
    ]
