# Generated by Django 5.2.10 on 2026-02-02 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udemy_app', '0007_submissionanswer_status_choices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_name',
        ),
    ]
