# Generated by Django 5.2.10 on 2026-02-02 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy_app', '0008_remove_userprofile_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udemy_app.course'),
        ),
    ]
