# Generated by Django 4.2.27 on 2026-02-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy_app', '0010_alter_course_teacher_alter_favorite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default=1, upload_to='course_image'),
            preserve_default=False,
        ),
    ]
